/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package usyd.distributed.scheduler.peacock.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-02")
public class TGlobalStateInfo implements org.apache.thrift.TBase<TGlobalStateInfo, TGlobalStateInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TGlobalStateInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TGlobalStateInfo");

  private static final org.apache.thrift.protocol.TField QUEUE_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("queueSize", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField WORK_LOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("workLoad", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("time", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TGlobalStateInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TGlobalStateInfoTupleSchemeFactory();

  public int queueSize; // required
  public long workLoad; // required
  public long time; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    QUEUE_SIZE((short)1, "queueSize"),
    WORK_LOAD((short)2, "workLoad"),
    TIME((short)3, "time");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // QUEUE_SIZE
          return QUEUE_SIZE;
        case 2: // WORK_LOAD
          return WORK_LOAD;
        case 3: // TIME
          return TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __QUEUESIZE_ISSET_ID = 0;
  private static final int __WORKLOAD_ISSET_ID = 1;
  private static final int __TIME_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.QUEUE_SIZE, new org.apache.thrift.meta_data.FieldMetaData("queueSize", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.WORK_LOAD, new org.apache.thrift.meta_data.FieldMetaData("workLoad", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TIME, new org.apache.thrift.meta_data.FieldMetaData("time", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TGlobalStateInfo.class, metaDataMap);
  }

  public TGlobalStateInfo() {
  }

  public TGlobalStateInfo(
    int queueSize,
    long workLoad,
    long time)
  {
    this();
    this.queueSize = queueSize;
    setQueueSizeIsSet(true);
    this.workLoad = workLoad;
    setWorkLoadIsSet(true);
    this.time = time;
    setTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TGlobalStateInfo(TGlobalStateInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.queueSize = other.queueSize;
    this.workLoad = other.workLoad;
    this.time = other.time;
  }

  public TGlobalStateInfo deepCopy() {
    return new TGlobalStateInfo(this);
  }

  @Override
  public void clear() {
    setQueueSizeIsSet(false);
    this.queueSize = 0;
    setWorkLoadIsSet(false);
    this.workLoad = 0;
    setTimeIsSet(false);
    this.time = 0;
  }

  public int getQueueSize() {
    return this.queueSize;
  }

  public TGlobalStateInfo setQueueSize(int queueSize) {
    this.queueSize = queueSize;
    setQueueSizeIsSet(true);
    return this;
  }

  public void unsetQueueSize() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __QUEUESIZE_ISSET_ID);
  }

  /** Returns true if field queueSize is set (has been assigned a value) and false otherwise */
  public boolean isSetQueueSize() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __QUEUESIZE_ISSET_ID);
  }

  public void setQueueSizeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __QUEUESIZE_ISSET_ID, value);
  }

  public long getWorkLoad() {
    return this.workLoad;
  }

  public TGlobalStateInfo setWorkLoad(long workLoad) {
    this.workLoad = workLoad;
    setWorkLoadIsSet(true);
    return this;
  }

  public void unsetWorkLoad() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WORKLOAD_ISSET_ID);
  }

  /** Returns true if field workLoad is set (has been assigned a value) and false otherwise */
  public boolean isSetWorkLoad() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WORKLOAD_ISSET_ID);
  }

  public void setWorkLoadIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WORKLOAD_ISSET_ID, value);
  }

  public long getTime() {
    return this.time;
  }

  public TGlobalStateInfo setTime(long time) {
    this.time = time;
    setTimeIsSet(true);
    return this;
  }

  public void unsetTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  /** Returns true if field time is set (has been assigned a value) and false otherwise */
  public boolean isSetTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  public void setTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIME_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case QUEUE_SIZE:
      if (value == null) {
        unsetQueueSize();
      } else {
        setQueueSize((java.lang.Integer)value);
      }
      break;

    case WORK_LOAD:
      if (value == null) {
        unsetWorkLoad();
      } else {
        setWorkLoad((java.lang.Long)value);
      }
      break;

    case TIME:
      if (value == null) {
        unsetTime();
      } else {
        setTime((java.lang.Long)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case QUEUE_SIZE:
      return getQueueSize();

    case WORK_LOAD:
      return getWorkLoad();

    case TIME:
      return getTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case QUEUE_SIZE:
      return isSetQueueSize();
    case WORK_LOAD:
      return isSetWorkLoad();
    case TIME:
      return isSetTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TGlobalStateInfo)
      return this.equals((TGlobalStateInfo)that);
    return false;
  }

  public boolean equals(TGlobalStateInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_queueSize = true;
    boolean that_present_queueSize = true;
    if (this_present_queueSize || that_present_queueSize) {
      if (!(this_present_queueSize && that_present_queueSize))
        return false;
      if (this.queueSize != that.queueSize)
        return false;
    }

    boolean this_present_workLoad = true;
    boolean that_present_workLoad = true;
    if (this_present_workLoad || that_present_workLoad) {
      if (!(this_present_workLoad && that_present_workLoad))
        return false;
      if (this.workLoad != that.workLoad)
        return false;
    }

    boolean this_present_time = true;
    boolean that_present_time = true;
    if (this_present_time || that_present_time) {
      if (!(this_present_time && that_present_time))
        return false;
      if (this.time != that.time)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + queueSize;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(workLoad);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(time);

    return hashCode;
  }

  @Override
  public int compareTo(TGlobalStateInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetQueueSize()).compareTo(other.isSetQueueSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQueueSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.queueSize, other.queueSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetWorkLoad()).compareTo(other.isSetWorkLoad());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWorkLoad()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.workLoad, other.workLoad);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetTime()).compareTo(other.isSetTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.time, other.time);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TGlobalStateInfo(");
    boolean first = true;

    sb.append("queueSize:");
    sb.append(this.queueSize);
    first = false;
    if (!first) sb.append(", ");
    sb.append("workLoad:");
    sb.append(this.workLoad);
    first = false;
    if (!first) sb.append(", ");
    sb.append("time:");
    sb.append(this.time);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TGlobalStateInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TGlobalStateInfoStandardScheme getScheme() {
      return new TGlobalStateInfoStandardScheme();
    }
  }

  private static class TGlobalStateInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<TGlobalStateInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TGlobalStateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // QUEUE_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.queueSize = iprot.readI32();
              struct.setQueueSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // WORK_LOAD
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.workLoad = iprot.readI64();
              struct.setWorkLoadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.time = iprot.readI64();
              struct.setTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TGlobalStateInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(QUEUE_SIZE_FIELD_DESC);
      oprot.writeI32(struct.queueSize);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(WORK_LOAD_FIELD_DESC);
      oprot.writeI64(struct.workLoad);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TIME_FIELD_DESC);
      oprot.writeI64(struct.time);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TGlobalStateInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TGlobalStateInfoTupleScheme getScheme() {
      return new TGlobalStateInfoTupleScheme();
    }
  }

  private static class TGlobalStateInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<TGlobalStateInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TGlobalStateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetQueueSize()) {
        optionals.set(0);
      }
      if (struct.isSetWorkLoad()) {
        optionals.set(1);
      }
      if (struct.isSetTime()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetQueueSize()) {
        oprot.writeI32(struct.queueSize);
      }
      if (struct.isSetWorkLoad()) {
        oprot.writeI64(struct.workLoad);
      }
      if (struct.isSetTime()) {
        oprot.writeI64(struct.time);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TGlobalStateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.queueSize = iprot.readI32();
        struct.setQueueSizeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.workLoad = iprot.readI64();
        struct.setWorkLoadIsSet(true);
      }
      if (incoming.get(2)) {
        struct.time = iprot.readI64();
        struct.setTimeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

