/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package usyd.distributed.scheduler.peacock.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-08-02")
public class TEnqueueProbeRequest implements org.apache.thrift.TBase<TEnqueueProbeRequest, TEnqueueProbeRequest._Fields>, java.io.Serializable, Cloneable, Comparable<TEnqueueProbeRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TEnqueueProbeRequest");

  private static final org.apache.thrift.protocol.TField PROBE_FIELD_DESC = new org.apache.thrift.protocol.TField("probe", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField GLOBAL_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("globalInfo", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TEnqueueProbeRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TEnqueueProbeRequestTupleSchemeFactory();

  public TFullProbe probe; // required
  public TGlobalStateInfo globalInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROBE((short)1, "probe"),
    GLOBAL_INFO((short)2, "globalInfo");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROBE
          return PROBE;
        case 2: // GLOBAL_INFO
          return GLOBAL_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROBE, new org.apache.thrift.meta_data.FieldMetaData("probe", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TFullProbe.class)));
    tmpMap.put(_Fields.GLOBAL_INFO, new org.apache.thrift.meta_data.FieldMetaData("globalInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TGlobalStateInfo.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TEnqueueProbeRequest.class, metaDataMap);
  }

  public TEnqueueProbeRequest() {
  }

  public TEnqueueProbeRequest(
    TFullProbe probe,
    TGlobalStateInfo globalInfo)
  {
    this();
    this.probe = probe;
    this.globalInfo = globalInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TEnqueueProbeRequest(TEnqueueProbeRequest other) {
    if (other.isSetProbe()) {
      this.probe = new TFullProbe(other.probe);
    }
    if (other.isSetGlobalInfo()) {
      this.globalInfo = new TGlobalStateInfo(other.globalInfo);
    }
  }

  public TEnqueueProbeRequest deepCopy() {
    return new TEnqueueProbeRequest(this);
  }

  @Override
  public void clear() {
    this.probe = null;
    this.globalInfo = null;
  }

  public TFullProbe getProbe() {
    return this.probe;
  }

  public TEnqueueProbeRequest setProbe(TFullProbe probe) {
    this.probe = probe;
    return this;
  }

  public void unsetProbe() {
    this.probe = null;
  }

  /** Returns true if field probe is set (has been assigned a value) and false otherwise */
  public boolean isSetProbe() {
    return this.probe != null;
  }

  public void setProbeIsSet(boolean value) {
    if (!value) {
      this.probe = null;
    }
  }

  public TGlobalStateInfo getGlobalInfo() {
    return this.globalInfo;
  }

  public TEnqueueProbeRequest setGlobalInfo(TGlobalStateInfo globalInfo) {
    this.globalInfo = globalInfo;
    return this;
  }

  public void unsetGlobalInfo() {
    this.globalInfo = null;
  }

  /** Returns true if field globalInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetGlobalInfo() {
    return this.globalInfo != null;
  }

  public void setGlobalInfoIsSet(boolean value) {
    if (!value) {
      this.globalInfo = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case PROBE:
      if (value == null) {
        unsetProbe();
      } else {
        setProbe((TFullProbe)value);
      }
      break;

    case GLOBAL_INFO:
      if (value == null) {
        unsetGlobalInfo();
      } else {
        setGlobalInfo((TGlobalStateInfo)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PROBE:
      return getProbe();

    case GLOBAL_INFO:
      return getGlobalInfo();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PROBE:
      return isSetProbe();
    case GLOBAL_INFO:
      return isSetGlobalInfo();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TEnqueueProbeRequest)
      return this.equals((TEnqueueProbeRequest)that);
    return false;
  }

  public boolean equals(TEnqueueProbeRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_probe = true && this.isSetProbe();
    boolean that_present_probe = true && that.isSetProbe();
    if (this_present_probe || that_present_probe) {
      if (!(this_present_probe && that_present_probe))
        return false;
      if (!this.probe.equals(that.probe))
        return false;
    }

    boolean this_present_globalInfo = true && this.isSetGlobalInfo();
    boolean that_present_globalInfo = true && that.isSetGlobalInfo();
    if (this_present_globalInfo || that_present_globalInfo) {
      if (!(this_present_globalInfo && that_present_globalInfo))
        return false;
      if (!this.globalInfo.equals(that.globalInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetProbe()) ? 131071 : 524287);
    if (isSetProbe())
      hashCode = hashCode * 8191 + probe.hashCode();

    hashCode = hashCode * 8191 + ((isSetGlobalInfo()) ? 131071 : 524287);
    if (isSetGlobalInfo())
      hashCode = hashCode * 8191 + globalInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TEnqueueProbeRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetProbe()).compareTo(other.isSetProbe());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProbe()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.probe, other.probe);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGlobalInfo()).compareTo(other.isSetGlobalInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGlobalInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.globalInfo, other.globalInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TEnqueueProbeRequest(");
    boolean first = true;

    sb.append("probe:");
    if (this.probe == null) {
      sb.append("null");
    } else {
      sb.append(this.probe);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("globalInfo:");
    if (this.globalInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.globalInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (probe != null) {
      probe.validate();
    }
    if (globalInfo != null) {
      globalInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TEnqueueProbeRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TEnqueueProbeRequestStandardScheme getScheme() {
      return new TEnqueueProbeRequestStandardScheme();
    }
  }

  private static class TEnqueueProbeRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<TEnqueueProbeRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TEnqueueProbeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROBE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.probe = new TFullProbe();
              struct.probe.read(iprot);
              struct.setProbeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // GLOBAL_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.globalInfo = new TGlobalStateInfo();
              struct.globalInfo.read(iprot);
              struct.setGlobalInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TEnqueueProbeRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.probe != null) {
        oprot.writeFieldBegin(PROBE_FIELD_DESC);
        struct.probe.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.globalInfo != null) {
        oprot.writeFieldBegin(GLOBAL_INFO_FIELD_DESC);
        struct.globalInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TEnqueueProbeRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TEnqueueProbeRequestTupleScheme getScheme() {
      return new TEnqueueProbeRequestTupleScheme();
    }
  }

  private static class TEnqueueProbeRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<TEnqueueProbeRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TEnqueueProbeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetProbe()) {
        optionals.set(0);
      }
      if (struct.isSetGlobalInfo()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetProbe()) {
        struct.probe.write(oprot);
      }
      if (struct.isSetGlobalInfo()) {
        struct.globalInfo.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TEnqueueProbeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.probe = new TFullProbe();
        struct.probe.read(iprot);
        struct.setProbeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.globalInfo = new TGlobalStateInfo();
        struct.globalInfo.read(iprot);
        struct.setGlobalInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

